<a href="https://colab.research.google.com/github/Versha217/Student-Performance-Prediction-YBI/blob/main/StudentPerformancePredictor.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [534]:
#import library
import pandas as pd

In [535]:
#read dataset
df=pd.read_csv('/content/Student Performance Predictor for EduQuest Coaching.csv')

In [536]:
df.head()

,gender,age,parental_education,family_income,internet_access,previous_exam_score,attendance_rate,homework_completion_rate,class_participation_score,number_of_absences,extra_curricular_involvement,learning_hours_per_week,tutor_support,final_exam_score
0,Male,14,Diploma,29591.84,Yes,93.25,91.01,76.56,9.52,1,Moderate,12.08,No,100.00
1,Male,16,Diploma,35222.46,Yes,85.06,83.85,64.82,3.42,2,Moderate,11.81,Yes,80.81
2,Male,14,Diploma,29730.93,Yes,79.93,86.71,75.02,3.75,1,Low,11.08,Yes,77.96
3,Female,15,Diploma,29074.09,Yes,98.94,88.04,55.50,6.95,0,Moderate,6.65,Yes,98.86
4,Male,19,Graduate,42305.33,Yes,64.54,61.22,98.85,6.03,5,Moderate,9.26,No,64.64

In [537]:
df.shape

(1000, 14)

In [538]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 14 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   gender                        1000 non-null   object
 1   age                           1000 non-null   int64
 2   parental_education            1000 non-null   object
 3   family_income                 1000 non-null   float64
 4   internet_access               1000 non-null   object
 5   previous_exam_score           1000 non-null   float64
 6   attendance_rate               1000 non-null   float64
 7   homework_completion_rate      1000 non-null   float64
 8   class_participation_score     1000 non-null   float64
 9   number_of_absences            1000 non-null   int64
 10  extra_curricular_involvement  628 non-null    object
 11  learning_hours_per_week       1000 non-null   float64
 12  tutor_support                 1000 non-null   object
 13  final_exam_score              1000 non-null   float64
dtypes: float64(7), int64(2), object(5)
memory usage: 109.5+ KB

In [539]:
df.isnull().sum()

gender                            0
age                               0
parental_education                0
family_income                     0
internet_access                   0
previous_exam_score               0
attendance_rate                   0
homework_completion_rate          0
class_participation_score         0
number_of_absences                0
extra_curricular_involvement    372
learning_hours_per_week           0
tutor_support                     0
final_exam_score                  0
dtype: int64

In [540]:
df['extra_curricular_involvement'].fillna('No_activity', inplace=True)

/tmp/ipykernel_4913/2153547956.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['extra_curricular_involvement'].fillna('No_activity', inplace=True)

In [541]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 14 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   gender                        1000 non-null   object
 1   age                           1000 non-null   int64
 2   parental_education            1000 non-null   object
 3   family_income                 1000 non-null   float64
 4   internet_access               1000 non-null   object
 5   previous_exam_score           1000 non-null   float64
 6   attendance_rate               1000 non-null   float64
 7   homework_completion_rate      1000 non-null   float64
 8   class_participation_score     1000 non-null   float64
 9   number_of_absences            1000 non-null   int64
 10  extra_curricular_involvement  1000 non-null   object
 11  learning_hours_per_week       1000 non-null   float64
 12  tutor_support                 1000 non-null   object
 13  final_exam_score              1000 non-null   float64
dtypes: float64(7), int64(2), object(5)
memory usage: 109.5+ KB

In [542]:
df.duplicated().sum()

np.int64(0)

In [543]:
df.describe(include='all')

,gender,age,parental_education,family_income,internet_access,previous_exam_score,attendance_rate,homework_completion_rate,class_participation_score,number_of_absences,extra_curricular_involvement,learning_hours_per_week,tutor_support,final_exam_score
count,1000,1000.000000,1000,1000.000000,1000,1000.00000,1000.000000,1000.000000,1000.000000,1000.000000,1000,1000.000000,1000,1000.000000
unique,2,NaN,4,NaN,2,NaN,NaN,NaN,NaN,NaN,4,NaN,2,NaN
top,Female,NaN,Diploma,NaN,Yes,NaN,NaN,NaN,NaN,NaN,No_activity,NaN,Yes,NaN
freq,504,NaN,321,NaN,864,NaN,NaN,NaN,NaN,NaN,372,NaN,567,NaN
mean,NaN,16.496000,NaN,40053.207840,NaN,69.92909,80.429630,74.312590,4.923780,1.979000,NaN,9.984440,NaN,76.024760
std,NaN,1.697901,NaN,9800.512538,NaN,14.30842,11.550007,14.572686,2.909478,1.448674,NaN,3.084464,NaN,11.214959
min,NaN,14.000000,NaN,14302.140000,NaN,30.00000,60.050000,50.040000,0.030000,0.000000,NaN,0.350000,NaN,39.840000
25%,NaN,15.000000,NaN,33566.487500,NaN,60.36750,70.547500,61.272500,2.325000,1.000000,NaN,7.955000,NaN,68.060000
50%,NaN,17.000000,NaN,40566.090000,NaN,69.93500,80.985000,74.265000,4.935000,2.000000,NaN,9.955000,NaN,76.270000
75%,NaN,18.000000,NaN,46650.012500,NaN,80.00750,90.380000,86.965000,7.425000,3.000000,NaN,12.080000,NaN,84.180000
max,NaN,19.000000,NaN,77007.250000,NaN,100.00000,99.990000,99.990000,9.990000,8.000000,NaN,21.170000,NaN,100.000000

In [544]:
#Checking distribution of values in the 'gender' column before encoding
df['gender'].value_counts()

gender
Female    504
Male      496
Name: count, dtype: int64

In [545]:
# Encode gender: Male as 0, Female as 1
df['gender']=df['gender'].replace({'Male':0, 'Female':1})

/tmp/ipykernel_4913/4050861201.py:2: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df['gender']=df['gender'].replace({'Male':0, 'Female':1})

In [546]:
# Verifying gender encoding
df['gender'].value_counts()

gender
1    504
0    496
Name: count, dtype: int64

In [547]:
#distribution of parental education levels
df['parental_education'].value_counts()

parental_education
Diploma         321
High School     290
Graduate        288
Postgraduate    101
Name: count, dtype: int64

In [548]:
# Encoding parental education as numbers
df['parental_education']=df['parental_education'].replace({'High School':0, 'Diploma':1, 'Graduate':2, 'Postgraduate':3})

/tmp/ipykernel_4913/2763784720.py:2: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df['parental_education']=df['parental_education'].replace({'High School':0, 'Diploma':1, 'Graduate':2, 'Postgraduate':3})

In [549]:
df['parental_education'].value_counts()

parental_education
1    321
0    290
2    288
3    101
Name: count, dtype: int64

In [550]:
# Check internet access counts
df['internet_access'].value_counts()

internet_access
Yes    864
No     136
Name: count, dtype: int64

In [551]:
# Encode internet access
df['internet_access']=df['internet_access'].replace({'No':0, 'Yes':1})

/tmp/ipykernel_4913/1419644615.py:2: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df['internet_access']=df['internet_access'].replace({'No':0, 'Yes':1})

In [552]:
df['internet_access'].value_counts()

internet_access
1    864
0    136
Name: count, dtype: int64

In [553]:
# Check extra curricular counts
df['extra_curricular_involvement'].value_counts()

extra_curricular_involvement
No_activity    372
Low            311
Moderate       224
High            93
Name: count, dtype: int64

In [554]:
# Encode extra curricular involvement
df['extra_curricular_involvement']=df['extra_curricular_involvement'].replace({'No_activity':0, 'Low':1, 'Moderate':2, 'High':3})

/tmp/ipykernel_4913/2829625045.py:2: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df['extra_curricular_involvement']=df['extra_curricular_involvement'].replace({'No_activity':0, 'Low':1, 'Moderate':2, 'High':3})

In [555]:
df['extra_curricular_involvement'].value_counts()

extra_curricular_involvement
0    372
1    311
2    224
3     93
Name: count, dtype: int64

In [556]:
# Check tutor support counts
df['tutor_support'].value_counts()

tutor_support
Yes    567
No     433
Name: count, dtype: int64

In [557]:
# Encode tutor support
df['tutor_support']=df['tutor_support'].replace({'Yes':1, 'No':0})

/tmp/ipykernel_4913/2110223059.py:2: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df['tutor_support']=df['tutor_support'].replace({'Yes':1, 'No':0})

In [558]:
df['tutor_support'].value_counts()

tutor_support
1    567
0    433
Name: count, dtype: int64

In [559]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 14 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   gender                        1000 non-null   int64
 1   age                           1000 non-null   int64
 2   parental_education            1000 non-null   int64
 3   family_income                 1000 non-null   float64
 4   internet_access               1000 non-null   int64
 5   previous_exam_score           1000 non-null   float64
 6   attendance_rate               1000 non-null   float64
 7   homework_completion_rate      1000 non-null   float64
 8   class_participation_score     1000 non-null   float64
 9   number_of_absences            1000 non-null   int64
 10  extra_curricular_involvement  1000 non-null   int64
 11  learning_hours_per_week       1000 non-null   float64
 12  tutor_support                 1000 non-null   int64
 13  final_exam_score              1000 non-null   float64
dtypes: float64(7), int64(7)
memory usage: 109.5 KB

In [560]:
# Show all column names
df.columns

Index(['gender', 'age', 'parental_education', 'family_income',
       'internet_access', 'previous_exam_score', 'attendance_rate',
       'homework_completion_rate', 'class_participation_score',
       'number_of_absences', 'extra_curricular_involvement',
       'learning_hours_per_week', 'tutor_support', 'final_exam_score'],
      dtype='object')

In [561]:
from sklearn.preprocessing import MinMaxScaler
import joblib

In [562]:
# Input features
X = df.drop('final_exam_score', axis=1)

# Target variable
y = df['final_exam_score']

# Verify
print("Shape of X:", X.shape)
print("Shape of y:", y.shape)

print(X.columns)

Shape of X: (1000, 13)
Shape of y: (1000,)
Index(['gender', 'age', 'parental_education', 'family_income',
       'internet_access', 'previous_exam_score', 'attendance_rate',
       'homework_completion_rate', 'class_participation_score',
       'number_of_absences', 'extra_curricular_involvement',
       'learning_hours_per_week', 'tutor_support'],
      dtype='object')

In [563]:
# Create a MinMaxScaler for the target variable
y_scaler = MinMaxScaler(feature_range=(0, 100))

# Fit and transform y
y_scaled = y_scaler.fit_transform(y.values.reshape(-1, 1))

In [564]:
#Train-test-split
from sklearn.model_selection import train_test_split



X_train, X_test, y_train, y_test = train_test_split(
    X, y_scaled, test_size=0.2, random_state=42
)


print("X_train shape:", X_train.shape)
print("X_test shape:", X_test.shape)
print("y_train shape:", y_train.shape)
print("y_test shape:", y_test.shape)

X_train shape: (800, 13)
X_test shape: (200, 13)
y_train shape: (800, 1)
y_test shape: (200, 1)

In [565]:
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

# Initialize model
model = LinearRegression()

# Train model on training data
model.fit(X_train, y_train)

LinearRegression()

In [566]:
# View intercept and coefficients
model.intercept_ , model.coef_

(array([-60.51576956]),
 array([[-7.47624497e-01,  7.66086908e-02,  3.94983637e-01,
         -1.03066617e-05, -2.15623174e+00,  6.31133303e-01,
          3.05663515e-01,  1.56182836e-01,  3.31855668e+00,
         -2.40180801e+00, -5.03465660e-02,  2.45247330e+00,
          8.89904417e+00]]))

In [567]:
# Make predictions on test data
y_pred = model.predict(X_test)

In [568]:
# Mean Absolute Error
mae = mean_absolute_error(y_test, y_pred)

# Mean Squared Error
mse = mean_squared_error(y_test, y_pred)

# R-squared
r2 = r2_score(y_test, y_pred)

print("MAE:", mae)
print("MSE:", mse)
print("R2 Score:", r2)

MAE: 7.40474507704851
MSE: 86.69744249671744
R2 Score: 0.7652550839132136

In [569]:
# Evaluate model using MAPE
from sklearn.metrics import mean_absolute_percentage_error

y_pred_scaled = model.predict(X_test)
mape = mean_absolute_percentage_error(y_test, y_pred_scaled)
print("MAPE:", mape)

MAPE: 0.14302338514159602

In [570]:
#  Import joblib
import joblib

# Assume your trained model is named 'model' (Linear Regression in your case)
# Save the model to a file

joblib.dump(model, "final_exam_predictor_model.pkl")
joblib.dump(y_scaler, "y_scaler.pkl")


print("Model saved successfully as 'final_exam_predictor_model.pkl'")

Model saved successfully as 'final_exam_predictor_model.pkl'

In [571]:
%%writefile app.py
import streamlit as st
import pandas as pd
import joblib

# Load the trained model
model = joblib.load('final_exam_predictor_model.pkl')
y_scaler = joblib.load('y_scaler.pkl')

MAX_SCORE = 350  # Maximum possible raw score

# ----------------------
# App Title
# ----------------------
st.set_page_config(page_title="Final Exam Score Predictor", page_icon="🎓", layout="wide")
st.title("🎓 Final Exam Score Predictor")
st.markdown("Predict the **final exam score** of a student based on key academic and personal factors.")

st.divider()

# ----------------------
# Input Sections
# ----------------------
st.header("👨‍🎓 Student Demographics")
col1, col2 = st.columns(2)
with col1:
    gender = st.selectbox('Gender', ['Male', 'Female'])
    age = st.number_input('Age', min_value=5, max_value=25, value=15)
    parental_education = st.selectbox('Parental Education', ['High School', 'Bachelor', 'Master', 'PhD'])
with col2:
    family_income = st.number_input('Family Income', min_value=0, value=50000)
    internet_access = st.selectbox('Internet Access', ['Yes', 'No'])
    tutor_support = st.selectbox('Tutor Support', ['Yes', 'No'])

st.divider()
st.header("📘 Academic Performance")
col3, col4 = st.columns(2)
with col3:
    previous_exam_score = st.number_input('Previous Exam Score', min_value=0, max_value=100, value=70)
    attendance_rate = st.number_input('Attendance Rate (%)', min_value=0, max_value=100, value=90)
    homework_completion_rate = st.number_input('Homework Completion Rate (%)', min_value=0, max_value=100, value=80)
with col4:
    class_participation_score = st.number_input('Class Participation Score', min_value=0, max_value=100, value=75)
    number_of_absences = st.number_input('Number of Absences', min_value=0, value=5)
    learning_hours_per_week = st.number_input('Learning Hours Per Week', min_value=0, value=10)
    extra_curricular_involvement = st.selectbox('Extra Curricular Involvement', ['No_activity', 'Low', 'Moderate', 'High'])

st.divider()

# ----------------------
# Encoding Inputs
# ----------------------
gender = 0 if gender == 'Male' else 1
internet_access = 1 if internet_access == 'Yes' else 0
tutor_support = 1 if tutor_support == 'Yes' else 0

extra_curricular_dict = {'No_activity': 0, 'Low': 1, 'Moderate': 2, 'High': 3}
extra_curricular_involvement = extra_curricular_dict[extra_curricular_involvement]

parental_education_dict = {'High School': 0, 'Bachelor': 1, 'Master': 2, 'PhD': 3}
parental_education = parental_education_dict[parental_education]

# ----------------------
# Create Input DataFrame
# ----------------------
input_data = pd.DataFrame({
    'gender': [gender],
    'age': [age],
    'parental_education': [parental_education],
    'family_income': [family_income],
    'internet_access': [internet_access],
    'previous_exam_score': [previous_exam_score],
    'attendance_rate': [attendance_rate],
    'homework_completion_rate': [homework_completion_rate],
    'class_participation_score': [class_participation_score],
    'number_of_absences': [number_of_absences],
    'extra_curricular_involvement': [extra_curricular_involvement],
    'learning_hours_per_week': [learning_hours_per_week],
    'tutor_support': [tutor_support]
})

# ----------------------
# Predict Button
# ----------------------
if st.button('Predict Final Exam Score'):
    # Predict scaled score
    scaled_pred = model.predict(input_data)
    # Convert scaled prediction back to raw score
    raw_prediction = y_scaler.inverse_transform(scaled_pred.reshape(-1, 1))[0][0]

    # Convert to percentage out of MAX_SCORE
    prediction_percent = (raw_prediction / MAX_SCORE) * 100

    # Determine grade based on percentage
    if prediction_percent >= 90:
        grade = 'A+'
    elif prediction_percent >= 80:
        grade = 'A'
    elif prediction_percent >= 70:
        grade = 'B+'
    elif prediction_percent >= 60:
        grade = 'B'
    elif prediction_percent >= 50:
        grade = 'C'
    else:
        grade = 'F'

    st.markdown("## 🏆 Prediction Result")
    st.success(f"**Predicted Final Exam Score (raw):** {raw_prediction:.2f}")
    st.success(f"**Predicted Score (scaled to 0-100%):** {prediction_percent:.2f}%")
    st.info(f"**Estimated Grade:** {grade}")

    st.write("### 📋 Input Summary")
    input_summary = input_data.copy()
    input_summary['gender'] = 'Male' if gender == 0 else 'Female'
    input_summary['internet_access'] = 'Yes' if internet_access == 1 else 'No'
    input_summary['tutor_support'] = 'Yes' if tutor_support == 1 else 'No'
    input_summary['parental_education'] = [k for k,v in parental_education_dict.items() if v == parental_education][0]
    input_summary['extra_curricular_involvement'] = [k for k,v in extra_curricular_dict.items() if v == extra_curricular_involvement][0]

    st.table(input_summary.T.rename(columns={0: "Value"}))

Overwriting app.py

In [572]:
!wget -O ngrok.zip https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-linux-amd64.zip

--2026-03-31 17:32:36--  https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-linux-amd64.zip
Resolving bin.equinox.io (bin.equinox.io)... 13.248.244.96, 75.2.60.68, 35.71.179.82, ...
Connecting to bin.equinox.io (bin.equinox.io)|13.248.244.96|:443... connected.
HTTP request sent, awaiting response... 500 Internal Server Error
2026-03-31 17:32:36 ERROR 500: Internal Server Error.

In [573]:
!curl -s https://ngrok-agent.s3.amazonaws.com/ngrok.asc | sudo tee /etc/apt/trusted.gpg.d/ngrok.asc >/dev/null
!echo "deb https://ngrok-agent.s3.amazonaws.com buster main" | sudo tee /etc/apt/sources.list.d/ngrok.list
!sudo apt update
!sudo apt install ngrok -y

deb https://ngrok-agent.s3.amazonaws.com buster main
Hit:1 http://security.ubuntu.com/ubuntu jammy-security InRelease
Hit:2 https://cloud.r-project.org/bin/linux/ubuntu jammy-cran40/ InRelease
Hit:3 https://cli.github.com/packages stable InRelease
Hit:4 http://archive.ubuntu.com/ubuntu jammy InRelease
Hit:5 http://archive.ubuntu.com/ubuntu jammy-updates InRelease
Hit:6 http://archive.ubuntu.com/ubuntu jammy-backports InRelease
Hit:7 https://r2u.stat.illinois.edu/ubuntu jammy InRelease
Hit:8 https://ngrok-agent.s3.amazonaws.com buster InRelease
Hit:9 https://ppa.launchpadcontent.net/deadsnakes/ppa/ubuntu jammy InRelease
Hit:10 https://ppa.launchpadcontent.net/ubuntugis/ppa/ubuntu jammy InRelease
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
24 packages can be upgraded. Run 'apt list --upgradable' to see them.
W: Skipping acquire of configured file 'main/source/Sources' as repository 'https://r2u.stat.illinois.edu/ubuntu jammy InRelease' does not seem to provide it (sources.list entry misspelt?)
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
ngrok is already the newest version (3.37.3).
0 upgraded, 0 newly installed, 0 to remove and 24 not upgraded.

In [574]:
!which ngrok

/usr/local/bin/ngrok

In [575]:
import os
import threading

def run_streamlit():
  os.system('streamlit run app.py --server.port 8501')

thread = threading.Thread(target = run_streamlit)
thread.start()

In [576]:

from pyngrok import ngrok, conf

conf.get_default().ngrok_path = "/usr/local/bin/ngrok"

ngrok.set_auth_token("3BiZ2RTuwTuGDjlp4iO8JqjNvgJ_7CHVwYFX17XXsXaNoXZqC")

public_url = ngrok.connect(8501)
print(public_url)

NgrokTunnel: "https://priestless-salina-subflexuously.ngrok-free.dev" -> "http://localhost:8501"